### ISSUE TITLE
Full Screen Support

### ISSUE THREAD

**Issue by neerajkumarc** [aayushchugh/FlipTimer#1]
Implement a fullscreen mode

**Comment by aayushchugh** [comment]
Thanks for the feedback. I'll definitely add it

**Comment by aayushchugh** [comment]
Added a full screen toggle button

<img width="1423" alt="image" src="https://github.com/user-attachments/assets/d96cb3cc-ee55-4b98-b658-0ce7b48a4653">

**Comment by aayushchugh** [comment]
We can toggle full screen by pressing `f` key too
